branch-defaults:
  master:
    environment: initializr-dev
    group_suffix: null
deploy:
  artifact: initializr-app/target/initializr.jar
option_settings:
  - option_name: GITHUB_USERNAME
    value: ${GITHUB_USERNAME}
  - option_name: GITHUB_PAT
    value: ${GITHUB_PAT}
global:
  application_name: initializr
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
