branch-defaults:
  master:
    environment: null
    group_suffix: null
deploy:
  artifact: initializr-app/target/initializr.jar
global:
  application_name: initializr
  branch: master
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
option_settings:
- option_name: GITHUB_USERNAME
  value: ${GITHUB_USERNAME}
- option_name: GITHUB_PAT
  value: ${GITHUB_PAT}
- namespace: aws:elasticbeanstalk:application
  option_name: Application Healthcheck URL
  value: /health
